services:
  - type: web
    name: atoka
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh startup.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: atoka_project.settings
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "atoka.onrender.com"
    autoDeploy: true
